### ISSUE TITLE
External directory (e.g. OpenLDAP/AD/JumpCloud) integration?

### ISSUE THREAD

**Issue by vicaya** [iGeeky/wolf#31]
It'd be great to have some external integration, so that the project can be used in an existing environment (already using OpenLDAP/AD on-prem or SaaS e.g. https://jumpcloud.com/). 

1. Authentication can be delegated to ldap (simple authentication) easily, which seems to be a low hanging fruit.
2. Authorization can be solved by associating roles to ldap user/group objects .

@iGeeky any thoughts/plans/roadmaps that could be shared?

**Comment by iGeeky** [comment]
You are right, LDAP integration for an RBAC system is very important, especially for companies that are already using LDAP systems.
About LDAP integration, because I have less experience in LDAP, may need to do some research first, to determine whether to support LDAP integration in the short term.
Some questions I can think of include:
Can all LDAP services be supported in one development? Or should each LDAP server be developed separately? My impression is that LDAP implementations from different manufacturers do not follow the standards exactly (far less compatibility between different SQL servers).
What is the integration method? Is it active synchronization of LDAP user information, or is synchronization triggered by user login? If LDAP groups are synchronized to Wolf groups, does the LDAP organization structure (e.g. departments) need to be synchronized/mapped to Wolf?
@vicaya  Do you have any suggestions about the above?
